services:
  python-app:
    build:
      dockerfile: Dockerfile
    ports:
      - "80:8000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgresql+psycopg2://postgres:567234@postgres:5432/rest_app"

  postgres:
    image: postgres:12
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: rest_app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 567234
